### PR TITLE
Prompt for elevation

### LINKED ISSUE #210: Can't start service - WMI Operation failure: AccessDenied
Hello!
Having problems with actual version on Windows 2012 R2.
Successfully installed service for nginx.exe with default minimal config. Starts with SYSTEM account.

If I start service (under administrator rights) with "net start" I got:
`System error 5 has occurred.
Access is denied.`

If I start service with "WinSW.NET4.exe start" I got:
`2017-04-21 11:35:01,236 INFO  - Starting ServiceWrapper in the CLI mode
2017-04-21 11:35:01,518 FATAL - WMI Operation failure: AccessDenied
WMI.WmiException: AccessDenied
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.InstanceHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
`
Thanks,
sukinsky

### PR DESCRIPTION
**Pull request by NextTurn**
Fixes #210 

The `status` command doesn't require privilege.

~The `restart`, `test` and `testwait` commands need some special care.~

The `restart!` command crashes without privileges.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Merge conflict

**Comment by NextTurn** [comment]
Scheduled for 2.8.

File: src/Core/ServiceWrapper/Main.cs [hunk 1]
```diff
@@ -935,6 +1033,34 @@ private static void InitLoggers(ServiceDescriptor d, bool enableCLILogging)
                 appenders.ToArray());
         }
 
+        private static unsafe bool IsProcessElevated()
```
Comment (oleg-nenashev) [inline src/Core/ServiceWrapper/Main.cs:1036]: I wish there was a safe version provided by .NET API. It is ok as a workaround

File: src/Core/ServiceWrapper/Main.cs [hunk 2]
```diff
@@ -935,6 +1033,34 @@ private static void InitLoggers(ServiceDescriptor d, bool enableCLILogging)
                 appenders.ToArray());
         }
 
+        private static unsafe bool IsProcessElevated()
+        {
+            IntPtr process = Kernel32.GetCurrentProcess();
+            if (!Advapi32.OpenProcessToken(process, TokenAccessLevels.Read, out IntPtr token))
+            {
+                throw new Win32Exception();
```
Comment (oleg-nenashev) [inline src/Core/ServiceWrapper/Main.cs:1041]: Add message ere for better diagnostincs?

File: src/Core/ServiceWrapper/Main.cs [hunk 3]
```diff
@@ -935,6 +1033,34 @@ private static void InitLoggers(ServiceDescriptor d, bool enableCLILogging)
...
+            try
+            {
+                if (!Advapi32.GetTokenInformation(
+                    token,
+                    TOKEN_INFORMATION_CLASS.TokenElevation,
+                    out TOKEN_ELEVATION elevation,
+                    sizeof(TOKEN_ELEVATION),
+                    out _))
+                {
+                    throw new Win32Exception();
```
Comment (oleg-nenashev) [inline src/Core/ServiceWrapper/Main.cs:1053]: same

File: src/Core/ServiceWrapper/Main.cs [hunk 4]
```diff
@@ -589,6 +591,21 @@ public static void Run(string[] _args, ServiceDescriptor? descriptor = null)
                 args = args.GetRange(2, args.Count - 2);
             }
 
+            bool elevated;
+            if (args[0] == "/elevated")
```
Comment (oleg-nenashev) [inline src/Core/ServiceWrapper/Main.cs:595]: Maybe it still makes sense to document it as internal argument. It can be used by advanced users who know what they are doing and want to improve performance a bit. No strong opinion

File: src/Core/ServiceWrapper/Main.cs (hunk 1 above)
Comment (NextTurn) [reply src/Core/ServiceWrapper/Main.cs:1036]: FTR there is another version.

```cs
using (WindowsIdentity identity = WindowsIdentity.GetCurrent())
{
    WindowsPrincipal principal = new WindowsPrincipal(identity);
    if (!principal.IsInRole(WindowsBuiltInRole.Administrator))
    {
        return;
    }
}
```

Comment (oleg-nenashev) [reply src/Core/ServiceWrapper/Main.cs:1036]: What is downside of this another option? AFAICT it is supported even in .NET Framework 2.0

Comment (NextTurn) [reply src/Core/ServiceWrapper/Main.cs:1036]: They are different. An elevated token isn't necessarily in the Administrators group.

> AFAICT it is supported even in .NET Framework 2.0

It reminds me that UAC was not invented on Windows XP. Do we still support Windows XP?

Comment (oleg-nenashev) [reply src/Core/ServiceWrapper/Main.cs:1036]: I definitely know some Jenkins users who still run Windows XP. Whether we want to support it or not, it is a separate question. I am happy to officially drop WinXP support once it becomes an obstacle.

Created https://github.com/winsw/winsw/issues/497 for Windows support policy documentation

File: src/Core/ServiceWrapper/Main.cs (hunk 4 above)
Comment (NextTurn) [reply src/Core/ServiceWrapper/Main.cs:595]: It makes more sense to add a `-no-elevate` argument. I'll add it as part of #433 if there is no priority.

Comment (oleg-nenashev) [reply src/Core/ServiceWrapper/Main.cs:595]: Agreed

**Comment by NextTurn** [comment]
Statistics show that #210 is the most popular issue.

image
